// Renders a markdown scorecard + an HTML dashboard, and diffs against the prior run.
import fs from 'node:fs';
import path from 'node:path';

const PREV = path.join('reports', 'previous-audit.json');

const EMOJI = { critical: '🔴', high: '🟠', medium: '🟡', low: '⚪' };

export function loadPrevious() {
  if (!fs.existsSync(PREV)) return null;
  try { return JSON.parse(fs.readFileSync(PREV, 'utf8')); } catch { return null; }
}

export function savePrevious(audit) {
  fs.mkdirSync('reports', { recursive: true });
  fs.writeFileSync(PREV, JSON.stringify(audit, null, 2));
}

function scoreDelta(audit, prev) {
  if (!prev) return '';
  const d = audit.score - prev.score;
  if (d === 0) return ' (no change)';
  return d > 0 ? ` (▲ +${d} since last run)` : ` (▼ ${d} since last run)`;
}

export function renderMarkdown(audit, fixResult, rankEntry, prev) {
  const lines = [];
  lines.push(`# 🧭 SEO Scorecard — ${audit.site}`);
  lines.push(`_Generated ${audit.auditedAt}_\n`);
  lines.push(`## Health Score: **${audit.score}/100**${scoreDelta(audit, prev)}`);
  lines.push(`- Pages crawled: **${audit.pageCount}**`);
  lines.push(`- Total issues: **${audit.totalIssues}**`);
  if (fixResult?.fixes?.length) lines.push(`- AI fixes generated: **${fixResult.fixes.length}**`);
  lines.push('');

  lines.push('## Issues by type');
  lines.push('| | Issue | Severity | Pages affected | Auto-fixable |');
  lines.push('|---|---|---|---|---|');
  for (const s of audit.summary) {
    lines.push(`| ${EMOJI[s.severity]} | \`${s.rule}\` | ${s.severity} | ${s.count} | ${s.fixable ? '✅' : '—'} |`);
  }
  lines.push('');

  if (prev) {
    const prevRules = new Set(prev.summary.map((s) => s.rule));
    const nowRules = new Set(audit.summary.map((s) => s.rule));
    const fixed = [...prevRules].filter((r) => !nowRules.has(r));
    const regressed = [...nowRules].filter((r) => !prevRules.has(r));
    if (fixed.length) lines.push(`### ✅ Resolved since last run\n${fixed.map((r) => `- \`${r}\``).join('\n')}\n`);
    if (regressed.length) lines.push(`### ⚠️ New since last run\n${regressed.map((r) => `- \`${r}\``).join('\n')}\n`);
  }

  if (rankEntry) {
    lines.push('## Keyword positions');
    lines.push('| Keyword | Position |');
    lines.push('|---|---|');
    for (const r of rankEntry.results) lines.push(`| ${r.keyword} | ${r.position ? `#${r.position}` : (r.note || 'not ranked')} |`);
    lines.push('');
  }

  if (fixResult?.fixes?.length) {
    lines.push('## AI-generated fixes (review before applying)');
    for (const f of fixResult.fixes.slice(0, 25)) {
      lines.push(`<details><summary><code>${f.url}</code> — ${f.addressed.join(', ')}</summary>\n`);
      lines.push('```json');
      lines.push(JSON.stringify(f.fix, null, 2));
      lines.push('```\n</details>\n');
    }
  }

  lines.push('\n---\n_Generated by Guide India SEO Automode._');
  return lines.join('\n');
}

export function renderHtml(audit, prev) {
  const rows = audit.summary
    .map((s) => `<tr><td>${EMOJI[s.severity]}</td><td><code>${s.rule}</code></td><td>${s.severity}</td><td>${s.count}</td><td>${s.fixable ? '✅' : '—'}</td></tr>`)
    .join('');
  const color = audit.score >= 80 ? '#16a34a' : audit.score >= 50 ? '#d97706' : '#dc2626';
  return `<!doctype html><html><head><meta charset="utf-8"><title>SEO Scorecard — ${audit.site}</title>
<style>body{font-family:system-ui,sans-serif;max-width:900px;margin:40px auto;padding:0 16px;color:#111}
.score{font-size:64px;font-weight:800;color:${color}}table{border-collapse:collapse;width:100%}
td,th{border:1px solid #e5e7eb;padding:8px 12px;text-align:left}th{background:#f9fafb}code{background:#f3f4f6;padding:2px 6px;border-radius:4px}</style></head>
<body><h1>🧭 SEO Scorecard</h1><p>${audit.site} — <small>${audit.auditedAt}</small></p>
<div class="score">${audit.score}<span style="font-size:24px;color:#6b7280">/100${prev ? ` (${audit.score - prev.score >= 0 ? '+' : ''}${audit.score - prev.score})` : ''}</span></div>
<p>${audit.pageCount} pages · ${audit.totalIssues} issues</p>
<table><thead><tr><th></th><th>Issue</th><th>Severity</th><th>Pages</th><th>Fixable</th></tr></thead><tbody>${rows}</tbody></table>
</body></html>`;
}

export function writeReports(audit, fixResult, rankEntry) {
  fs.mkdirSync('reports', { recursive: true });
  const prev = loadPrevious();
  const md = renderMarkdown(audit, fixResult, rankEntry, prev);
  const html = renderHtml(audit, prev);
  fs.writeFileSync(path.join('reports', 'scorecard.md'), md);
  fs.writeFileSync(path.join('reports', 'scorecard.html'), html);
  fs.writeFileSync(path.join('reports', 'latest-audit.json'), JSON.stringify(audit, null, 2));
  if (fixResult) fs.writeFileSync(path.join('reports', 'fixes.json'), JSON.stringify(fixResult, null, 2));
  savePrevious(audit);
  return { md, html };
}
